#!/bin/sh

mkdir -p opk
cp ./stuntcarracer opk/
cp ./icon32.png opk/icon.png
cp -r Bitmap opk/
cp -r Sounds opk/
cp -r Tracks opk/
cp DejaVuSans-Bold.ttf opk/

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

print '[Desktop Entry]
Type=Application
Name=Stunt Car Racer
Comment=3D racing game
Exec=stuntcarracer
Icon=icon
Terminal=false
Type=Application
Categories=games;
' > opk/default."$1".desktop

mksquashfs ./opk stuntcarracer_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
